version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: chat_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "0804"
      MYSQL_DATABASE: "chatdb"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chat_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  chat_server:
    build: .
    container_name: chat_server
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - chat_network
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: "0804"
      MYSQL_DATABASE: chatdb

volumes:
  mysql_data:


networks:
  chat_network:
    driver: bridge
